import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcrypt'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding database...')

  // Create admin user
  const adminPassword = await bcrypt.hash('admin123', 10)
  const admin = await prisma.user.upsert({
    where: { email: 'admin@ecommerce.com' },
    update: {},
    create: {
      email: 'admin@ecommerce.com',
      password: adminPassword,
      name: 'Admin User',
      role: 'ADMIN',
    },
  })
  console.log('✅ Created admin user:', admin.email)

  // Create agent users
  const agentPassword = await bcrypt.hash('agent123', 10)
  const agent1 = await prisma.user.upsert({
    where: { email: 'agent1@ecommerce.com' },
    update: {},
    create: {
      email: 'agent1@ecommerce.com',
      password: agentPassword,
      name: 'Sarah Johnson',
      role: 'AGENT',
    },
  })
  console.log('✅ Created agent user:', agent1.email)

  // Create sample customers
  const customer1 = await prisma.customer.upsert({
    where: { email: 'john.doe@example.com' },
    update: {},
    create: {
      email: 'john.doe@example.com',
      name: 'John Doe',
      phone: '+1234567890',
    },
  })
  console.log('✅ Created customer:', customer1.email)

  // Create sample FAQs
  const faqs = [
    {
      question: 'What is your shipping policy?',
      answer: 'We offer free shipping on orders over $50. Standard shipping takes 3-5 business days. Express shipping is available for an additional fee and delivers in 1-2 business days.',
      category: 'Shipping',
      tags: ['shipping', 'delivery', 'policy'],
    },
    {
      question: 'How do I return an item?',
      answer: 'You can return items within 30 days of purchase. Visit our returns portal, enter your order number, and follow the instructions. Refunds are processed within 5-7 business days after we receive your return.',
      category: 'Returns',
      tags: ['returns', 'refund', 'policy'],
    },
    {
      question: 'Do you offer international shipping?',
      answer: 'Yes, we ship to over 50 countries worldwide. International shipping rates vary by location and are calculated at checkout. Delivery times range from 7-21 business days depending on the destination.',
      category: 'Shipping',
      tags: ['shipping', 'international', 'worldwide'],
    },
    {
      question: 'How can I track my order?',
      answer: 'Once your order ships, you\'ll receive a tracking number via email. You can also track your order by logging into your account and viewing your order history.',
      category: 'Orders',
      tags: ['tracking', 'order', 'shipment'],
    },
    {
      question: 'What payment methods do you accept?',
      answer: 'We accept all major credit cards (Visa, MasterCard, American Express, Discover), PayPal, Apple Pay, and Google Pay.',
      category: 'Payment',
      tags: ['payment', 'checkout', 'methods'],
    },
  ]

  for (const faq of faqs) {
    await prisma.fAQ.create({
      data: {
        question: faq.question,
        answer: faq.answer,
        category: faq.category,
        tags: faq.tags.join(','), // Convert array to comma-separated string
        embedding: null, // Embeddings will be generated by AI service
      },
    })
  }
  console.log('✅ Created sample FAQs')

  // Create sample conversations
  const conversation1 = await prisma.conversation.create({
    data: {
      customerId: customer1.id,
      agentId: agent1.id,
      status: 'ACTIVE',
      sentiment: 'NEUTRAL',
    },
  })

  await prisma.message.createMany({
    data: [
      {
        conversationId: conversation1.id,
        content: 'Hi, I ordered a laptop 3 days ago but haven\'t received tracking information yet.',
        sender: 'CUSTOMER',
        timestamp: new Date(Date.now() - 1000 * 60 * 10), // 10 minutes ago
      },
      {
        conversationId: conversation1.id,
        content: 'Hello! I\'d be happy to help you with that. Let me look into your order.',
        sender: 'AGENT',
        agentId: agent1.id,
        timestamp: new Date(Date.now() - 1000 * 60 * 9), // 9 minutes ago
      },
      {
        conversationId: conversation1.id,
        content: 'My order number is #12345',
        sender: 'CUSTOMER',
        timestamp: new Date(Date.now() - 1000 * 60 * 8), // 8 minutes ago
      },
    ],
  })

  const customer2 = await prisma.customer.upsert({
    where: { email: 'jane.smith@example.com' },
    update: {},
    create: {
      email: 'jane.smith@example.com',
      name: 'Jane Smith',
      phone: '+1234567891',
    },
  })

  const conversation2 = await prisma.conversation.create({
    data: {
      customerId: customer2.id,
      agentId: agent1.id,
      status: 'ACTIVE',
      sentiment: 'POSITIVE',
    },
  })

  await prisma.message.createMany({
    data: [
      {
        conversationId: conversation2.id,
        content: 'I need to return a product. What\'s your return policy?',
        sender: 'CUSTOMER',
        timestamp: new Date(Date.now() - 1000 * 60 * 5), // 5 minutes ago
      },
      {
        conversationId: conversation2.id,
        content: 'You can return items within 30 days of purchase. Would you like me to initiate a return?',
        sender: 'AGENT',
        agentId: agent1.id,
        aiSuggestion: 'Based on our return policy FAQ, you can return items within 30 days.',
        aiConfidence: 0.95,
        timestamp: new Date(Date.now() - 1000 * 60 * 4), // 4 minutes ago
      },
    ],
  })

  console.log('✅ Created sample conversations')

  console.log('✨ Seeding completed!')
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
